"""add international_incidents table

Revision ID: 4cec761cf03e
Revises: dc5d705dabe1
Create Date: 2026-02-06 15:31:00.042390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cec761cf03e'
down_revision: Union[str, None] = 'dc5d705dabe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('airport_code', sa.String(length=10), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_international_incidents_airport_code'), ['airport_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_incidents_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_incidents_incident_date'), ['incident_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_incidents_incident_id'), ['incident_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_international_incidents_incident_id'))
        batch_op.drop_index(batch_op.f('ix_international_incidents_incident_date'))
        batch_op.drop_index(batch_op.f('ix_international_incidents_country_code'))
        batch_op.drop_index(batch_op.f('ix_international_incidents_airport_code'))

    op.drop_table('international_incidents')
    # ### end Alembic commands ###
