"""초기 스키마: risk_assessments, category_score_records

Revision ID: 9f4f4db1019d
Revises: 
Create Date: 2026-02-06 10:46:46.126047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4f4db1019d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_code', sa.String(length=10), nullable=False),
    sa.Column('airport_name', sa.String(length=50), nullable=False),
    sa.Column('assessed_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_code', 'assessed_date', name='uq_airport_date')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_airport_code'), ['airport_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_assessed_date'), ['assessed_date'], unique=False)

    op.create_table('category_score_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_score_records')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_assessed_date'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_airport_code'))

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
