"""add weight_histories table

Revision ID: dc5d705dabe1
Revises: 9f4f4db1019d
Create Date: 2026-02-06 14:31:10.753109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5d705dabe1'
down_revision: Union[str, None] = '9f4f4db1019d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('category_weights', sa.JSON(), nullable=False),
    sa.Column('factor_weights', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('analysis_period_start', sa.Date(), nullable=True),
    sa.Column('analysis_period_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_histories_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_histories_is_active'))

    op.drop_table('weight_histories')
    # ### end Alembic commands ###
