"""add news_articles table

Revision ID: dd9c3b86c884
Revises: 4cec761cf03e
Create Date: 2026-02-06 16:07:33.101812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9c3b86c884'
down_revision: Union[str, None] = '4cec761cf03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('airport_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_airport_code'), ['airport_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_article_id'), ['article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_category'))
        batch_op.drop_index(batch_op.f('ix_news_articles_article_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_airport_code'))

    op.drop_table('news_articles')
    # ### end Alembic commands ###
